# Generated by Django 4.2.11 on 2024-04-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourrecord',
            old_name='teamlead_email',
            new_name='Organizer_Email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ymp_id',
        ),
        migrations.RemoveField(
            model_name='hourrecord',
            name='next_week_plans',
        ),
        migrations.RemoveField(
            model_name='hourrecord',
            name='ymp_id',
        ),
        migrations.AddField(
            model_name='hourrecord',
            name='user_id',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
