# Generated by Django 4.2.11 on 2024-04-07 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_teamlead_email_hourrecord_organizer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default=0, max_length=5000)),
                ('Organization_Logo', models.CharField(max_length=5000)),
                ('Organization_Name', models.CharField(max_length=500)),
                ('Organization_Email', models.EmailField(max_length=254, verbose_name='email address')),
                ('Organization_Description', models.CharField(max_length=500)),
            ],
        ),
    ]
