# Generated by Django 4.2.11 on 2024-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userType',
            field=models.CharField(default='Volunteer', max_length=500),
        ),
    ]
