# Generated by Django 4.2.11 on 2024-04-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_events_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participants_list',
            field=models.CharField(default='[]', max_length=20000),
        ),
        migrations.AlterField(
            model_name='hourrecord',
            name='date',
            field=models.CharField(default=0, max_length=5000),
        ),
    ]
