# Generated by Django 4.2.11 on 2024-04-07 16:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_event_participants_list_alter_hourrecord_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='participants_list',
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participated', to=settings.AUTH_USER_MODEL),
        ),
    ]
